format_version: 10

pipelines:

  nbb_build_publish_pipeline:
    
    group: NodeBulletinBoardApplication

    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: 1
    environment_variables:

    materials:
      git:
        git: https://github.com/sqaisar/node-bulletin-board.git
        shallow_clone: true
        auto_update: true
        branch: master

    stages:

    - nbb_build_publish_stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success

        jobs:

          build_image:

            timeout: 0
            elastic_profile_id: demo-app

            artifacts:

            - external:
                id: bulletin-board
                store_id: dockerhub
                configuration:
                  options:
                    Image: ${DOCKERHUB_USERNAME}/bulletin-board
                    Tag: ${GO_PIPELINE_LABEL}
            tasks:
            
            - exec:
                arguments:
                - -c
                - docker build -t $DOCKERHUB_USERNAME/bulletin-board:$GO_PIPELINE_LABEL . -f Dockerfile.application
                command: /bin/bash
                run_if: passed
