format_version: 10

pipelines:

  nbb_claybox_deployment_pipeline:

    group: NodeBulletinBoardApplication
    lock_behavior: unlockWhenFinished
    display_order: 3
    
    materials:
      
      upstream:
        pipeline: nbb_test_application_pipeline
        stage: nbb_test_application_stage
        name: upstream_pipeline
      
      gitRepository:
        git: "https://github.com/sqaisar/k8-deployment-manifests.git"
        branch: master
        username: sqaisar
        encrypted_password: AES:tCJvJQsZXrptroUqwLabKg==:favHDMsURUh6yt+20fX2WuMJU5wctHiOd81uM5caDQuh0VTz5d1cB3dad4UzdjM1
    
    stages:
      - nbb_claybox_deployment_stage:

          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false

          approval:
            type: success

          jobs:

            deployment:

              timeout: 0
              elastic_profile_id: agent-profile

              tasks:

              - fetch:

                  artifact_id: bulletin-board
                  pipeline: nbb_build_publish_pipeline/nbb_test_application_pipeline
                  stage: nbb_build_publish_stage
                  job: build_image
                  artifact_origin: external
                  run_if: passed

                  options:
                    EnvironmentVariablePrefix: ''
                    SkipImagePulling: 'true'

              - script: |
                  echo "Generating manifests! Although they are already generated :)"
                  pwd
                  ls -a ./

